### ISSUE TITLE
相比于https://proxy.cocopilot.org作为上游地址有什么优势？

### ISSUE THREAD

**Issue by 14790897** [Yanyutin753/gpt4-copilot-java-sh#1]

**Comment by Yanyutin753** [comment]
上游只能用cocopilot 本项目适用于把copilot官网，cocopilot，以及你从淘宝或者第三方平台拿到的自定义copilot网址转成api

**Comment by 14790897** [comment]
求教，假如淘宝拿到了token和url为什么不能直接使用

**Comment by Yanyutin753** [comment]
需要修改自定义获取token的地址，改成你淘宝的那个地址，之后用淘宝拿到的token请求部署服务，具体你看文档，写得很清楚了

**Comment by 14790897** [comment]
好的，🤩
