### ISSUE TITLE
佬儿～有没有可能可以使用gpt-4-mobile或者gpt-4-s模型配合inker呢

### ISSUE THREAD

**Issue by kkklilili** [Yanyutin753/gpt4-copilot-java-sh#3]
rt

**Comment by Yanyutin753** [comment]
copilot没有这个的 换我那个refreshtov1api

**Comment by kkklilili** [comment]
got it，目前就是ninja+2api。
不过ninja不维护了才看下copilot。看来copilot只能用于文字

**Comment by kkklilili** [comment]
got it，目前就是ninja+2api。
不过ninja不维护了才看下copilot。看来copilot只能用于文字
